name: Docker Volume Test

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: [self-hosted, macOS, X64, test1]

    steps:
    - uses: actions/checkout@v3
    - name: Hello, World
      run: echo 'Hello World'
