name: Docker Volume Test

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: [self-hosted, macOS, X64, test1]

    steps:
    - uses: actions/checkout@v3
    - name: Running MySQL
      run: docker run -p 3306:3306 --name=mysql -e MYSQL_ROOT_PASSWORD=root -d mysql:latest
