name: Docker Volume Test

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: [self-hosted, macOS, X64, test1]
    
    container:
      image: mysql:8.0
      env:
        MYSQL_DATABASE: test_db
        MYSQL_USER: test1
        MYSQL_PASSWORD: test1
        MYSQL_ROOT_PASSWORD: root
      
      ports:
        - 3306:3306

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Permission Check
      run: |
        ls -lart
    - name: Clean the workspace
      run: |
        shopt -s dotglob
        rm -rf $GITHUB_WORKSPACE/*
        
    - name: Running MySQL
      run: docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -d mysql:latest
